apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: text-to-speech-db
  namespace: default
spec:
  instances: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: text_to_speech
      owner: app
  monitoring:
    enablePodMonitor: true
