apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: text-to-speech
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: tts-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
