name: End-to-End Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Setup Node.js
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: homepage/package-lock.json

      - name: Install dependencies
        run: |
          cd homepage
          npm ci

      - name: Start server and run tests
        run: |
          cd homepage
          npm run dev &
          npx wait-on http://localhost:5173 --timeout 60000
          npm run cy:run

  tts-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Run TTS Integration Test
        run: |
          cd text-to-speech
          cargo test --test integration_test
