name: Integration Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Install Kind
        run: |
          curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64" --retry 5 --retry-connrefused --retry-max-time 60
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Run Integration Tests
        run: ./integration-tests/run.sh
