name: Integration Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Setup toolcache
        run: |
          mkdir -p /opt/hostedtoolcache
          chown -R $(whoami) /opt/hostedtoolcache

      - name: Setup Kind
        uses: https://github.com/helm/kind-action@v1
        with:
          cluster_name: integration-test
          wait: 60s

      - name: Run Integration Tests
        run: ./integration-tests/run.sh
