name: Integration Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup Python
        uses: https://github.com/actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Setup Kind
        uses: https://github.com/helm/kind-action@v1
        with:
          cluster_name: integration-test
          wait: 60s

      - name: Run Integration Tests
        run: ./integration-tests/run.sh
