apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-db
  namespace: temporal
spec:
  instances: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      postInitSQL:
        - CREATE DATABASE temporal_visibility OWNER temporal;
  monitoring:
    enablePodMonitor: true
