apiVersion: v1
kind: Service
metadata:
  name: speech-to-text
  namespace: default
  labels:
    app: speech-to-text
spec:
  selector:
    app: speech-to-text
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
