apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: speedtest-db
spec:
  instances: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: speedtest
      owner: app
      secret:
        name: speedtest-db-app-user
  monitoring:
    enablePodMonitor: true
