apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: location-share-server
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: location-share-server
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
