export interface TaskInput {
  /** Unique task ID (UUID, generated by submitter) */
  taskId: string;
  /** The prompt to send to Claude Code */
  prompt: string;
  /** Working directory for Claude Code (absolute path on worker) */
  workDir: string;
  /** Max time in seconds for Claude Code execution. Default: 1800 (30 min) */
  timeoutSeconds?: number;
  /** Additional CLI flags passed to claude */
  extraFlags?: string[];
  /** Metadata for result consumers */
  metadata?: Record<string, string>;
}

export interface TaskResult {
  taskId: string;
  /** Workflow ID in Temporal */
  workflowId: string;
  status: "completed" | "failed" | "timed_out";
  /** Claude Code JSON output (stdout) */
  output?: string;
  /** stderr if failed */
  error?: string;
  /** Wall-clock duration in milliseconds */
  durationMs: number;
  /** Which worker handled it */
  workerId: string;
  /** ISO 8601 timestamp */
  completedAt: string;
  /** Passthrough metadata from the input */
  metadata?: Record<string, string>;
}
