apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-scraper
  namespace: temporal
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: web-scraper
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
