apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whatsapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: whatsapp
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
